# build is triggered on commits and PRs to the following branches
branches:
  # whitelist
  only:
    - master

image: Visual Studio 2019

environment:
  matrix:
  - PYTHON: C:\Python38

install:
- set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
- ps: $env:BUILD_NUMBER_OR_TAG_NAME=&{If($env:APPVEYOR_REPO_TAG -eq "true") {"$env:APPVEYOR_REPO_TAG_NAME"} Else {"$env:APPVEYOR_BUILD_NUMBER$env:APPVEYOR_REPO_COMMIT"}}
- ps: echo $env:BUILD_NUMBER_OR_TAG_NAME
- echo %BUILD_NUMBER_OR_TAG_NAME%
- failfast
- python -m pip install pyinstaller

# run a custom scripts instead of automatic MSBuild
build_script:
- mkdir build
- cd build
- python -m PyInstaller ../hello_world.py
- 7z a hello_world-windows-x86.zip ./dist/hello_world/

artifacts:
  - path: hello_world.py
    name: python_script

  - path: build/hello_world-windows-x86.zip
    name: windows_executable

deploy:
  description: 'Initial Version'
  provider: GitHub
  auth_token:
    secure: l6RQlR9p5XLRsTH5GtTs4HMR3b819qt5wDzgQUN2zHjbgVdEMkS83Kojsvwp7Qqt
  artifact: python_script, windows_executable
  draft: false
  on:
    APPVEYOR_REPO_TAG: true

