# build is triggered on commits and PRs to the following branches
branches:
  # whitelist
  only:
    - master

image: Visual Studio 2019

environment:
  matrix:
  - PYTHON: C:\Python38

install:
- set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
- python -m pip install pyinstaller

# run a custom scripts instead of automatic MSBuild
build_script:
- mkdir build
- cd build
- python -m PyInstaller --onefile ../hello_world.py

artifacts:
  - path: hello_world.py
    name: python_script

  - path: build/dist/hello_world.exe
    name: windows_executable

deploy:
  description: 'Initial Version'
  provider: GitHub
  auth_token:
    secure: l6RQlR9p5XLRsTH5GtTs4HMR3b819qt5wDzgQUN2zHjbgVdEMkS83Kojsvwp7Qqt
  artifact: python_script, windows_executable
  draft: false
  on:
    APPVEYOR_REPO_TAG: true

