# branches to build
branches:
  # whitelist
  only:
    - master

# Start builds on tags only
skip_non_tags: true

image: Visual Studio 2019

environment:
  matrix:
  - PYTHON: C:\Python38

install:
- set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
- ps: >-
    If (!(Test-Path venv/)) {
      python -m venv venv
      venv/Scripts/Activate.ps1
      ./build_and_install_pyinstaller.ps1
      deactivate
    }
- venv/Scripts/activate.bat

cache:
  - '%APPVEYOR_BUILD_FOLDER%\venv\ -> build_and_install_pyinstaller.ps1, appveyor.yml'

# run a custom scripts instead of automatic MSBuild
build_script:
- mkdir build
- pushd build
- python -m PyInstaller --onefile ../hello_world.py
- popd

artifacts:
  - path: hello_world.py
    name: python_script

  - path: build/dist/hello_world.exe
    name: windows_executable

deploy:
  description: 'Initial Version'
  provider: GitHub
  auth_token:
    secure: l6RQlR9p5XLRsTH5GtTs4HMR3b819qt5wDzgQUN2zHjbgVdEMkS83Kojsvwp7Qqt
  artifact: python_script, windows_executable
  draft: true

